<template>
  <AppLayout>
    <div class="p-6">
      <h1 class="text-2xl font-bold mb-4">Maintenance Alerts</h1>
      <p class="mb-6 text-sm text-gray-600 dark:text-gray-300">
        The following table shows recent road alerts generated by RoadFAI's monitoring system.
      </p>

      <div class="overflow-x-auto border rounded">
        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead class="bg-gray-100 dark:bg-gray-800">
            <tr>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Zone</th>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Issue</th>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Reported At</th>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Severity</th>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Status</th>
              <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 dark:text-gray-300">Action</th>
            </tr>
          </thead>
          <tbody class="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
            <tr v-for="alert in paginatedAlerts" :key="alert.id">
              <td class="px-4 py-2 text-sm text-gray-700 dark:text-gray-300">{{ alert.zone }}</td>
              <td class="px-4 py-2 text-sm text-gray-700 dark:text-gray-300">{{ alert.issue }}</td>
              <td class="px-4 py-2 text-sm text-gray-700 dark:text-gray-300">{{ alert.reportedAt }}</td>
              <td class="px-4 py-2 text-sm font-semibold" :class="{
                'text-green-600': alert.severity === 'Low',
                'text-yellow-500': alert.severity === 'Medium',
                'text-red-600': alert.severity === 'High'
              }">
                {{ alert.severity }}
              </td>
              <td class="px-4 py-2 text-sm font-medium" :class="{
                'text-green-600': alert.status === 'Resolved',
                'text-yellow-500': alert.status === 'In Progress',
                'text-red-600': alert.status === 'Unresolved'
              }">
                {{ alert.status }}
              </td>
              <td class="px-4 py-2">
                <button
                  v-if="alert.status !== 'Resolved'"
                  @click="markResolved(alert.id)"
                  class="px-3 py-1 text-xs bg-green-600 text-white rounded hover:bg-green-700"
                >
                  Mark as Resolved
                </button>
                <span v-else class="text-xs text-gray-400">No Action Needed</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="mt-4 flex justify-between items-center">
        <button @click="prevPage" :disabled="currentPage === 1" class="px-3 py-1 bg-gray-300 rounded disabled:opacity-50">Prev</button>
        <span>Page {{ currentPage }} of {{ totalPages }}</span>
        <button @click="nextPage" :disabled="currentPage === totalPages" class="px-3 py-1 bg-gray-300 rounded disabled:opacity-50">Next</button>
      </div>
    </div>
  </AppLayout>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { Head } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';

const zoneList = ['North', 'South', 'East', 'West'];
const issueList = ['Pothole Detected', 'Sensor Offline', 'Flood Risk Detected', 'CCTV Malfunction'];
const severityList = ['Low', 'Medium', 'High'];
const statusList = ['Unresolved', 'In Progress', 'Resolved'];
const alerts = ref(Array.from({ length: 50 }, (_, i) => ({
  id: i + 1,
  zone: zoneList[i % zoneList.length],
  issue: issueList[i % issueList.length],
  reportedAt: `2025-07-${(Math.floor(Math.random() * 28) + 1).toString().padStart(2, '0')} ${8 + i % 12}:00`,
  severity: severityList[i % severityList.length],
  status: statusList[i % statusList.length],
})));

function markResolved(id: number) {
  const alert = alerts.value.find(a => a.id === id);
  if (alert) alert.status = 'Resolved';
}

const currentPage = ref(1);
const perPage = 10;
const totalPages = computed(() => Math.ceil(alerts.value.length / perPage));
const paginatedAlerts = computed(() => {
  const start = (currentPage.value - 1) * perPage;
  return alerts.value.slice(start, start + perPage);
});
function prevPage() {
  if (currentPage.value > 1) currentPage.value--;
}
function nextPage() {
  if (currentPage.value < totalPages.value) currentPage.value++;
}
</script>
